theme: jekyll-theme-slate
title: Welcome to ConControls!
author: Ren√© Vogt
description: ConControls is a library for Windows console ui controls.
url: https://renevogt.github.io/ConControls/
markdown: kramdown
exclude: api/
